import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ContactModal from "./component/modal/ContactModal";
import LoginModal from "./component/modal/LoginModal";
import RegisterModal from "./component/modal/RegisterModal";
import { GoogleOAuthProvider } from '@react-oauth/google';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || ''}>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <ContactModal />
        <LoginModal />
        <RegisterModal />
      </body>
    </html>
    </GoogleOAuthProvider>
  );
}
